#+TITLE: Zero to One by Peter Thiel
#+AUTHOR: Elliot Penson

Progress may be horizontal or vertical. *Horizontal progress* is the duplication
of things that work - going from 1 to /n/. *Vertical progress* is the creation
of new things - going from 0 to 1. Globalization is horizontal
progress. Technology is vertical progress.

#+BEGIN_QUOTE
Technology is miraculous because it allows us to do more with less, ratcheting
up our fundamental capabilities to a higher level...Humans don't decide what
to build by making choices from some cosmic catalog of options given in advance;
instead, by creating new technologies, we rewrite the plan of the world.
#+END_QUOTE

The contrarian question asks "What important truth do very few people agree with
you on?" Good answers to this question are glimpses into the future. Thiel's
answer to the contrarian question is that "most people think the future of the
world will be defined by globalization, but the truth is that technology matters
more."

#+BEGIN_QUOTE
New technology tends to come from new ventures - startups...Startups operate on
the principle that you need to work with other people to get stuff done, but you
also need to stay small enough so that you actually can.
#+END_QUOTE

* Conventional Beliefs

  #+BEGIN_QUOTE
  The contrarian question is difficult to answer directly. It may be easier to
  start with a preliminary: what does everybody agree on? ...Conventional
  beliefs only ever come to appear arbitrary and wrong in retrospect; whenever
  one collapses, we call the old belief a *bubble*.
  #+END_QUOTE

  The dot-com boom of the late 90s was intense but short. The dot-com /bust/
  taught Silicon Valley four big lessons that still guide business thinking
  today:

  1. Make incremental advances
  2. Stay lean and flexible (code for "unplanned")
  3. Improve on competition
  4. Focus on product, not sales

  Yet, the opposite principles are probably more correct.

  1. It is better to risk boldness than triviality.
  2. A bad plan is better than no plan.
  3. Competitive markets destroy profits.
  4. Sales matters just as much as product.

  #+BEGIN_QUOTE
  To build the next generation of companies, we must abandon the dogmas created
  after the crash. That doesn't mean the opposite ideas are automatically true:
  you can't escape the madness of crowds by dogmatically rejecting
  them. Instead ask yourself: how much of what you know about business is shaped
  by mistaken reactions to past mistakes? The most contrarian thing of all is
  not to oppose the crowd but to think for yourself.
  #+END_QUOTE
