#+TITLE: Amazon SNS
#+AUTHOR: Elliot Penson

Amazon Simple Notification Service (SNS) is a web service for setting up,
operating, and sending notifications from the cloud. It provides developers with
a highly scalable, flexible, and cost-effective capability to publish messages
from an application and immediately deliver them to subscribers or other
applications.

Amazon SNS follows the "publish-subscribe" (pub-sub) messaging paradigm, with
notifications being delivered to clients using a "push" mechanism that
eliminates the need to periodically check or "poll" for new information and
updates.

With simple APIs requiring minimal up-front development effort, no maintenance
or management overhead and pay-as-you-go pricing, Amazon SNS gives developers an
easy mechanism to incorporate a powerful notification system with their
applications.

* Delivery

  Besides pushing cloud notifications directly to mobile devices, Amazon SNS can
  also deliver notifications by SMS text message or email to Amazon Simple Queue
  Service (SQS) queues, or to any HTTP endpoint.

  SNS notifications can also trigger Lambda functions. When a message is
  published to an SNS topic that has a Lambda function subscribed to it, the
  Lambda function is invoked with the payload of the published message.

  To prevent messages from being lost, all messages published to Amazon SNS are
  stored redundantly across multiple availability zones. Pricing is different
  for the different delivery types.

* SNS Topics

  SNS allows you to group multiple recipients using topics. A topic is an
  "access point" for allowing recipients to dynamically subscribe for identical
  copies of the same notification.

  One topic can support deliveries to multiple endpoint types -- for example,
  you can group together iOS, Android, and SMS recipients. When you publish once
  to a topic, SNS delivers appropriately formatted copies of your message to
  each subscriber.

* Benefits

  - Instantaneous, push-based delivery (no polling).
  - Simple APIs and easy integration with applications.
  - Flexible message delivery over multiple transport protocols.
  - Inexpensive, pay-as-you-go model with no up-front costs.
  - Web-based AWS Management Console offers the simplicity of a point-and-click
    interface.

* SNS vs. SQS

  Both messaging services. SNS is push, SQS is poll (pull).

* SNS vs. SES

  Amazon Simple Email Service (SES) is email-only. It's good for automated
  emails, newsletters, and advertisements. SES /just/ requires an email address,
  SNS requires a subscription.
