#+TITLE: Containers
#+AUTHOR: Elliot Penson

A *container* is a lightweight linux environment that lets one package
application pieces into a hermetic, deployable unit. Containers raise the
abstraction layer from idealized hardware (virtual machines) to idealized
operating systems. Developers care about containers because...

- the static application environment makes deployments more *reliable*.
- the repeatable, runnable artifact makes code *portable*.
- applications are *loosely coupled* and can be organized as microservices.
- the consistent framework is particularly *automatable*.

*Container images* bundle a program and its runtime/dependencies into a single
artifact under a root filesystem. Images also include additional metadata used
by a *container runtime* to start a running application based on the contents of
the container image. Container images become containers at runtime.

A *container orchestrator* (such as [[file:kubernetes.org][Kubernetes]]) are tools which group containers
to form clusters. Orchestrators provide fault-tolerance, scalability, optimal
resource usage, auto-discovery, and deployments.

A *container registry* (such as ECR, GCR, and Docker Registry) enables sharing
by storing images which may be later pulled by others.

Also see [[file:docker.org][Docker]].
